
package domain;

public enum Brand {
	SEAT("SEAT", "SEAT"), CITROEN("CITROEN", "CITROEN"), GENERAL("GENERAL", "GENERAL"), VOLKSWAGEN("VOLKSWAGEN", "VOLKSWAGEN"), FIAT("FIAT", "FIAT"), DODGE("DODGE", "DODGE"), FORD("FORD", "FORD"), FERRARI("FERRARI", "FERRARI"), KIA("KIA", "KIA"), SSANGYONG(
		"SSANGYONG", "SSANGYONG"), NISSAN("NISSAN", "NISSAN"), DACIA("DACIA", "DACIA"), HONDA("HONDA", "HONDA"), ALFA_ROMEO("ALFA ROMEO", "ALFA ROMEO"), ASTON_MARTIN("ASTON MARTIN", "ASTON MARTIN"), AUDI("AUDI", "AUDI"), BENTLEY("BENTLEY", "BENTLEY"), BMW(
		"BMW", "BMW"), HYUNDAI("HYUNDAI", "HYUNDAI"), INFINITI("INFINITI", "INFINITI"), JAGUAR("JAGUAR", "JAGUAR"), JEEP("JEEP", "JEEP"), MAHINDRA("MAHINDRA", "MAHINDRA"), LAND_ROVER("LAND ROVER", "LAND ROVER"), LOTUS("LOTUS", "LOTUS"), LEXUS("LEXUS",
		"LEXUS"), MASERATI("MASERATI", "MASERATI"), MAZDA("MAZDA", "MAZDA"), MERCEDES_BENZ("MERCEDES BENZ", "MERCEDES BENZ"), MINI("MINI", "MINI"), MITSUBISHI("MITSUBISHI", "MITSUBISHI"), OPEL("OPEL", "OPEL"), PEUGEOT("PEUGEOT", "PEUGEOT"), RENAULT(
		"RENAULT", "RENAULT"), SKODA("SKODA", "SKODA"), SMART("SMART", "SMART"), SUBARU("SUBARU", "SUBARU"), SUZUKI("SUZUKI", "SUZUKI"), TESLA("TESLA", "TESLA"), VOLVO("VOLVO", "VOLVO"), IVECO("IVECO", "IVECO"), TATA("TATA", "TATA"), FISHER("FISHER",
		"FISHER"), SCANIA("SCANIA", "SCANIA"), MAN("MAN", "MAN"), ISUZU("ISUZU", "ISUZU"), GMC("GMC", "GMC"), HINO("HINO", "HINO"), HUMMER("HUMMER", "HUMMER"), CHEVROLET("CHEVROLET", "CHEVROLET"), FOTON("FOTON", "FOTON"), FUSCA("FUSCA", "FUSCA"), LANCIA(
		"LANCIA", "LANCIA"), CADILLAC("CADILLAC", "CADILLAC"), CHANA("CHANA", "CHANA"), OTROS("OTHER", "OTRO");

	private final String	name;
	private final String	spanishName;


	private Brand(final String name, final String spanishName) {
		this.name = name;
		this.spanishName = spanishName;
	}

	public String getName() {
		return this.name;
	}

	public String getSpanishName() {
		return this.spanishName;
	}

}
